[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://srv-daodhgo473hc739trl00.onrender.com"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
